feature_to_service_mapping = {
    "Login-Signup": ["Cognito"],
    "Profile Management": ["RDS", "EC2"],
    "Image Post": ["S3", "EC2"],
    "Video Post": ["S3", "MediaLive", "MediaConvert"],
    "Text Post": ["RDS", "EC2"],
    "Live Streaming": ["MediaLive"],
    "Chat": ["RDS", "EC2"],
    "Comments": ["RDS", "EC2"],
    "Likes": ["RDS", "EC2"],
    "Sharing": ["S3", "EC2"],
    "Notifications": ["RDS"],
    "Search and Filters": ["RDS"],
    "Product Listings": ["RDS", "S3"],
    "Shopping Cart": ["RDS"],
    "Checkout": ["RDS", "S3"],
    "Payment Gateway": ["RDS"],
    "Order Tracking": ["RDS"],
    "User Reviews": ["RDS"],
    "Wishlist": ["RDS"],
    "Video Streaming": ["MediaLive"],
    "Media Processing": ["MediaConvert"],
    "Appointment Scheduling": ["RDS"],
    "Telemedicine": ["EC2"],
    "EHR Integration": ["RDS"],
    "Payment Processing": ["RDS"],
    "Account Management": ["RDS"],
    "Investment Tracking": ["RDS"],
    "Service Listings": ["RDS", "S3"],
    "Booking System": ["RDS"],
    "Order Tracking": ["RDS"],
    "User Reviews": ["RDS"]
}
